---
abstract: 'Set a theme (dressing) in your widget and its children.'
author:
  - 'Djibril Ousmanou <djibel@cpan.org>'
build_requires:
  Config::Std: 0.007
  File::Basename: 0
  File::Copy: 0
  File::Spec: 0
  Test::More: 0
  Tk: 800
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3601'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tk-Dressing
provides:
  Tk::Dressing:
    file: lib/Tk/Dressing.pm
    version: 1.01
resources:
  license: http://dev.perl.org/licenses/
version: 1.01
